name: CI
on: [push, pull_request]

concurrency: # Cancel stale PR builds (but not push builds)
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        nim:
          - '1.6.0'
          - '2.0.0'
          - '1.6.x'
          - '2.0.x'
          - 'devel'
        os:
          -  ubuntu-latest
    name: Nim ${{ matrix.nim }} / ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
      - name: Setup nim
        uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Download nimble
        run: |
          curl -Ls https://github.com/nim-lang/nimble/releases/download/latest/nimble-linux_x64.tar.gz | tar xz
          mv nimble $(which nimble)
      - name: Setup dependencies
        run: nimble install -l -d -y
      - name: Run tests
        run: nimble test -y
      - name: Run benchmarks
        run: nimble bench -y
